services:
  postgres_db:
    container_name: 'postgres_db'
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpostgres
      - POSTGRES_DB=devhub
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: